name: meeter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_splash_screen: ^3.0.0
  #introduction_screen: ^1.0.7
  page_transition: 1.1.7+6
  url_launcher: ^5.7.10
  font_awesome_flutter: ^8.11.0
  firebase_auth: ^0.20.0+1
  flutter_spinkit: ^4.1.2+1
  achievement_view: ^0.2.1
  firebase_core: ^0.7.0
  firebase_messaging: 8.0.0-dev.14
  provider: ^4.3.2+4
  strings: ^0.1.4
  uuid: ^2.2.2
  circular_profile_avatar: ^1.0.8
  image_picker: ^0.6.7+21
  giffy_dialog: ^1.8.0
  #im_animations: ^0.1.1
  shared_preferences: ^0.5.12+4
  move_to_background: ^1.0.1
  #gradient_text: ^1.0.2
  #animate_icons: ^1.0.0
  chips_choice: ^2.0.1
  #flutter_icons: ^1.1.0
  #dots_indicator: ^1.2.0
  #flutter_staggered_grid_view: ^0.3.2
  #flutter_point_tab_bar: ^0.1.0
  getwidget: ^1.2.4
  #animated_bottom_navigation_bar: ^0.2.1
  #syncfusion_flutter_datepicker: ^18.4.34-beta
  #cupertino_icons: ^1.0.0
  #expandable_text: ^1.3.2
  #photo_view: ^0.10.3
  #launch_review: ^2.0.0
  #clipboard_manager: ^0.0.4
  #awesome_dialog: ^1.3.1
  permission_handler: ^5.0.1+1
  intl_phone_number_input: ^0.5.0
  cloud_firestore: ^0.16.0+1
  #android_power_manager: ^0.1.6
  firebase_storage: ^7.0.0
  #direct_select_flutter: ^1.0.7
  #lazy_data_table: ^0.2.1
  #list_tile_more_customizable: ^1.3.3
  #flutter_slidable: ^0.4.9
  #blurhash: 0.2.0
  #emoji_picker: ^0.1.0
  #modal_progress_hud: ^0.1.3
  #flutter_colorpicker: ^0.3.5
  #timeago: ^2.0.30
  pinput: ^1.0.0
  textfield_tags: ^1.1.1
  #flutter_rounded_date_picker: 1.0.5+1
  flutter_statusbarcolor: ^0.2.3
  #tabbar: ^0.1.1
  readmore: ^1.0.1
  #some_calendar: ^1.2.6
  #jiffy: 3.0.1
  syncfusion_flutter_calendar: ^18.4.49
  timer_count_down: 1.0.4+1
  date_picker_timeline: ^1.2.0 
  #flutter_zoom_drawer: 1.0.5
  curved_navigation_bar: 0.3.7
  google_maps_flutter:
  geolocator:
  #navigation_action_bar: ^0.0.1
  spincircle_bottom_bar: ^1.0.0
  



  



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/flare/meeter.flr
    - assets/images/Logo@2x.png
    - assets/images/Videoconferencing.png
    - assets/images/Apple.png
    - assets/images/Google.png
    - assets/images/Facebook.png
    - assets/images/Twitter.png
    - assets/images/verification.png
    - assets/images/verified.png
    - assets/images/female.png
    - assets/images/male.png
    - assets/images/image.png
    - assets/images/1pic.png
    - assets/images/2pic.png
    - assets/images/3pic.png
    - assets/images/4pic.png
    - assets/images/dp1.png
    - assets/images/dp2.png
    - assets/images/dp3.png
    - assets/images/Group 10208.png
    - assets/images/data/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Black.ttf
          weight: 900
        - asset: fonts/Nunito-BlackItalic.ttf
          weight: 900
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito-BoldItalic.ttf
          weight: 700
        - asset: fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: fonts/Nunito-ExtraBoldItalic.ttf
          weight: 800
        - asset: fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: fonts/Nunito-ExtraLightItalic.ttf
          weight: 200
        - asset: fonts/Nunito-Italic.ttf
          weight: 400
        - asset: fonts/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito-LightItalic.ttf
          weight: 300
        - asset: fonts/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito-SemiBoldItalic.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/poppins/Poppins-Black.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
